language: ruby

rvm:
  - 2.2.6
  - 2.3.3
  - 2.4.0

script:
  - ruby ./VMTranslator.rb ./StackArithmetic/StackTest/StackTest.vm > ./StackArithmetic/StackTest/StackTest.asm
  - ./tools/CPUEmulator.sh ./StackArithmetic/StackTest/StackTest.tst
  - ruby ./VMTranslator.rb ./ProgramFlow/BasicLoop/BasicLoop.vm > ./ProgramFlow/BasicLoop/BasicLoop.asm
  - ./tools/CPUEmulator.sh ./ProgramFlow/BasicLoop/BasicLoop.tst
  - ruby ./VMTranslator.rb ./ProgramFlow/FibonacciSeries/FibonacciSeries.vm > ./ProgramFlow/FibonacciSeries/FibonacciSeries.asm
  - ./tools/CPUEmulator.sh ./ProgramFlow/FibonacciSeries/FibonacciSeries.tst
  - ruby ./VMTranslator.rb ./MemoryAccess/StaticTest/StaticTest.vm > ./MemoryAccess/StaticTest/StaticTest.asm
  - ./tools/CPUEmulator.sh ./MemoryAccess/StaticTest/StaticTest.tst
